version: '3.7'
services:
  mongo:
    image: leafney/alpine-mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD}
      MONGO_INITDB_DATABASE: empress
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    env_file: .env
    command: mongod --bind_ip 127.0.0.1,172.18.0.2
    #add bind_ip = <ip> in "/data/config/mongod.conf" to accept connections
  backend:
    build: .
    environment:
      NODE_ENV: development
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
    command: npm start
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: development
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    depends_on:
      - "backend"
    command: yarn start
  #maybe removed in prod
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on:
      - mongo
    env_file: .env